modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="robotica"
version="0.7.0"
displayName="Robotica"
displayURL="https://www.nightbeam.cloud"
logoFile="logo.png"
credits="moonrayys <3"
authors="NightBeamStudio"
description="Robotica is a futuristic Minecraft mod set in a high-tech world filled with advanced robots, towering mechs, and powerful sci-fi weapons."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.robotica]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.robotica]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration